// Generated by CoffeeScript 1.9.3
(function($){
	$(window).on('load',function(){
		//横幅いっぱい
		var $slide2 = $('.bxslider2');
		var $slide2_ul = $slide2.find('.bxslider > ul');
		var n = $slide2_ul.children('li').size();
		$slide2_ul.bxSlider({
				maxSlides: 2,
				easing: 'easeOutExpo',
				auto: 'true', //オート
				speed: '800', //切り替わるスピード
				pause: '3000', //待機時間
				autoHover: false,//マウスオーバー時停止
				autoControls: false,//再生・停止ボタン
				controls: true,//NEXTボタン・PREVボタン
				pager: true,//スライドナビ				
				controls: true,
				onSliderLoad: function(){
					$slide2.find('.bx-viewport > ul').css({
						width: n * 100 + 415 + '%'
					});
					$slide2_ul.animate({
						opacity: 1
					},500);
				}
			}
		);
	});
})(jQuery);
